/**
 * Types for the Mini Apps mode.
 *
 * A mini-app is a small self-contained HTML+CSS+JS application generated by
 * the LLM and run inside a sandboxed WebView. Each mini-app is tightly coupled
 * to a single chat thread (1 chat <-> 1 app); iteration replaces the app's
 * files in place and bumps `version`.
 *
 * Persistence layout:
 *
 *   AsyncStorage key "tensorchat_miniapps_index"  (lightweight index, fast grid render)
 *   <DocumentDirectory>/miniapps/<appId>/
 *     index.html   generated wrapper: CSP meta + reset + sandbox shim + inlined CSS + HTML + JS
 *     style.css    raw CSS as authored by the LLM
 *     app.js       raw JS as authored by the LLM
 *     meta.json    { name, emoji, version, chatId, createdAt, updatedAt } — written LAST
 */

/**
 * Storage schema version. Bumped whenever the on-disk meta.json or the
 * AsyncStorage index shape changes in a backwards-incompatible way.
 * The startup migration in `storage.ts` uses this to wipe legacy apps
 * that can't be loaded into the current runtime.
 *
 * Version history:
 *   1 — raw html/css/js shape (deprecated, pre-component-runtime)
 *   2 — single `program` field using the `tc` component runtime
 */
export const MINIAPP_STORAGE_VERSION = 2;

// Re-export the identity type from `identity.ts` so consumers can pull
// MiniApp + MiniAppIdentity from a single module without crossing into
// runtime-side imports. The actual derivation logic stays in identity.ts.
export type { MiniAppIdentity } from "./identity";

export interface MiniAppMeta {
  name: string;
  emoji: string;
  version: number;
  chatId: string;
  createdAt: number;
  updatedAt: number;
  /**
   * Storage format version. Present on all apps written under v2+.
   * Apps without this field are v1 (raw html/css/js) and are skipped
   * by the loader.
   */
  schemaVersion?: number;
}

export interface MiniApp extends MiniAppMeta {
  id: string;
  /**
   * The single JS program emitted by the LLM, calling into the `tc`
   * component runtime. This is the ONLY user-authored code in the app
   * — the html shell, CSS theme, and runtime are all owned by
   * `src/miniapps/runtime/`.
   */
  program: string;
}

/** Lightweight index entry stored in AsyncStorage for the home grid. */
export interface MiniAppIndexEntry {
  id: string;
  chatId: string;
  name: string;
  emoji: string;
  version: number;
  updatedAt: number;
  /**
   * Number of snapshots present in the app's `history/` subdirectory.
   * Used to gate the undo button in the mini-app chat view: the button
   * is only shown when `historyDepth > 0`. Populated on every index
   * write and backfilled by `readIndex` for apps that predate this
   * field (returning 0 for them).
   */
  historyDepth?: number;
}

/**
 * Input to the storage write path. Discriminated union: NEW apps require
 * the caller to supply name + emoji (typically derived via
 * `deriveAppIdentity` from the first user prompt); ITERATIONS reuse the
 * existing app's identity from disk and only need the new program.
 *
 * The agent's `write_mini_app` tool only emits `program`; the tool's
 * `execute` chooses between the two variants based on whether an app
 * already exists for the chat.
 */
export type WriteMiniAppInput =
  | WriteNewMiniAppInput
  | WriteMiniAppIterationInput;

export interface WriteNewMiniAppInput {
  kind: "new";
  chatId: string;
  name: string;
  emoji: string;
  program: string;
}

export interface WriteMiniAppIterationInput {
  kind: "iteration";
  id: string;
  chatId: string;
  program: string;
}

/** Runtime error posted back from the sandboxed WebView. */
export interface RuntimeError {
  message: string;
  source?: string;
  line?: number;
  col?: number;
  stack?: string;
}

/**
 * Tracks the verification window after each successful write.
 * Runtime errors during this window trigger an auto-retry through the Agent.
 */
export interface VerificationState {
  chatId: string;
  appId: string;
  version: number;
  startedAt: number;
  deadlineAt: number;
  attemptsUsed: number;
}

export const MINIAPP_VERIFY_WINDOW_MS = 2500;
export const MINIAPP_MAX_AUTO_RETRIES = 3;
export const MINIAPP_INDEX_STORAGE_KEY = "tensorchat_miniapps_index";
export const SELECTED_MINIAPP_MODEL_KEY = "tensorchat_selected_miniapp_model";
