import { Footer } from '../components/Footer'

export function TermsOfService() {
  return (
    <div className="min-h-screen bg-base text-text-primary font-sans">
      {/* Simple nav */}
      <header className="border-b border-border-subtle">
        <nav className="max-w-3xl mx-auto px-6 md:px-8 h-16 flex items-center">
          <a href="/" className="flex items-center gap-2.5">
            <img src="/icon-ready.png" alt="TensorChat" className="w-7 h-7 rounded-lg" />
            <span className="font-display text-lg font-semibold text-text-primary tracking-tight">
              TensorChat
            </span>
          </a>
        </nav>
      </header>

      <main className="max-w-3xl mx-auto px-6 md:px-8 py-16 lg:py-24">
        <h1 className="font-display text-3xl lg:text-4xl font-bold tracking-tight mb-3">
          Terms of Service
        </h1>
        <p className="text-sm text-text-tertiary mb-12">Last updated: March 30, 2026</p>

        <div className="prose-custom space-y-8 text-text-secondary leading-[1.8] text-[15px]">
          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using TensorChat ("the App"), you agree to be bound by
              these Terms of Service. If you do not agree to these terms, do not use the App.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Description of Service</h2>
            <p>
              TensorChat is a mobile application that enables on-device AI language model inference.
              The App runs AI models locally on your device without requiring cloud connectivity for
              core functionality. The App is provided free of charge.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc list-inside space-y-1.5 mt-3">
              <li>Use the App in compliance with all applicable laws and regulations</li>
              <li>Not use the App to generate harmful, illegal, or abusive content</li>
              <li>Not reverse engineer, decompile, or disassemble the App beyond what is permitted by law</li>
              <li>Not redistribute or sublicense the App or its components</li>
              <li>Take responsibility for any content generated using the App</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">AI-Generated Content</h2>
            <p>
              Content generated by AI models through TensorChat is produced by open-source language
              models running on your device. We make no warranties about the accuracy, completeness,
              or reliability of AI-generated content. You are solely responsible for evaluating and
              using any content generated by the App.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Third-Party Models</h2>
            <p>
              TensorChat provides access to open-source AI models hosted on HuggingFace and other
              repositories. These models are subject to their own licenses and terms. By downloading
              and using these models, you agree to comply with their respective license terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Intellectual Property</h2>
            <p>
              The TensorChat application, including its design, code, and branding, is the property
              of its developers. Open-source components are used under their respective licenses.
              Content you create using the App belongs to you.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Disclaimer of Warranties</h2>
            <p>
              The App is provided "as is" and "as available" without warranties of any kind, either
              express or implied. We do not warrant that the App will be uninterrupted, error-free,
              or free of harmful components. AI model outputs may be inaccurate, biased, or inappropriate.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, in no event shall the developers of TensorChat
              be liable for any indirect, incidental, special, consequential, or punitive damages,
              or any loss of profits or data, arising out of or in connection with your use of the App.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. Changes will be
              posted on this page with an updated revision date. Continued use of the App after
              changes constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Termination</h2>
            <p>
              You may stop using the App at any time by uninstalling it. Since the App does not
              require an account, there is no account termination process. All locally stored data
              is removed when you uninstall the App.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-text-primary mb-3">Contact</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:support@tensorchat.app" className="text-accent hover:underline">
                support@tensorchat.app
              </a>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}
